language: python
sudo: false

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio run
    - platformio run -d ArduinoCode/i2c-gps
