language: python

python:
- '2.7'

env:
- PROJECT=adem
- PROJECT=i2c-slave

sudo: false

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
  directories:
  - ~/.platformio

install:
- pip install -U platformio

script:
- platformio run -d $PROJECT
